import { type ThievingTarget } from '../calc/types';
import { ThievingRealmId } from '../constants/item-ids';

export const MELVOR_TARGETS: ThievingTarget[] = [
  // Low Town
  {
    id: 'melvorF:Man',
    name: 'Man',
    area: 'Low Town',
    realmId: ThievingRealmId.MELVOR,
    level: 1,
    baseExperience: 5,
    maxHit: 22,
    perception: 110,
    currencyRange: { min: 1, max: 100 },
    currencyType: 'gp',
  },
  {
    id: 'melvorF:Woman',
    name: 'Woman',
    area: 'Low Town',
    realmId: ThievingRealmId.MELVOR,
    level: 4,
    baseExperience: 7,
    maxHit: 32,
    perception: 140,
    currencyRange: { min: 1, max: 150 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Fine Coinpurse', dropQuantity: { min: 1, max: 1 } },
  },
  // Golbin Village
  {
    id: 'melvorF:Golbin',
    name: 'Golbin',
    area: 'Golbin Village',
    realmId: ThievingRealmId.MELVOR,
    level: 8,
    baseExperience: 10,
    maxHit: 40,
    perception: 175,
    currencyRange: { min: 1, max: 175 },
    currencyType: 'gp',
  },
  {
    id: 'melvorF:Golbin_Chief',
    name: 'Golbin Chief',
    area: 'Golbin Village',
    realmId: ThievingRealmId.MELVOR,
    level: 16,
    baseExperience: 18,
    maxHit: 101,
    perception: 280,
    currencyRange: { min: 1, max: 275 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Golbin Mask', dropQuantity: { min: 1, max: 1 } },
  },
  // Bandit Hideout
  {
    id: 'melvorF:Bandit_Thug',
    name: 'Bandit Thug',
    area: 'Bandit Hideout',
    realmId: ThievingRealmId.MELVOR,
    level: 12,
    baseExperience: 13,
    maxHit: 54,
    perception: 220,
    currencyRange: { min: 1, max: 200 },
    currencyType: 'gp',
  },
  {
    id: 'melvorF:Marauder',
    name: 'Marauder',
    area: 'Bandit Hideout',
    realmId: ThievingRealmId.MELVOR,
    level: 21,
    baseExperience: 19,
    maxHit: 68,
    perception: 250,
    currencyRange: { min: 1, max: 225 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Absorbing Shield', dropQuantity: { min: 1, max: 1 } },
  },
  // Banquet
  {
    id: 'melvorF:Assistant_Cook',
    name: 'Assistant Cook',
    area: 'Banquet',
    realmId: ThievingRealmId.MELVOR,
    level: 26,
    baseExperience: 26,
    maxHit: 86,
    perception: 275,
    currencyRange: { min: 1, max: 250 },
    currencyType: 'gp',
    uniqueDrop: { name: "Chef's Spoon", dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorF:Chef',
    name: 'Chef',
    area: 'Banquet',
    realmId: ThievingRealmId.MELVOR,
    level: 34,
    baseExperience: 31,
    maxHit: 108,
    perception: 350,
    currencyRange: { min: 1, max: 300 },
    currencyType: 'gp',
    uniqueDrop: { name: "Chef's Hat", dropQuantity: { min: 1, max: 1 } },
  },
  // Farmer's Market
  {
    id: 'melvorF:Merchant',
    name: 'Merchant',
    area: "Farmer's Market",
    realmId: ThievingRealmId.MELVOR,
    level: 31,
    baseExperience: 29,
    maxHit: 97,
    perception: 300,
    currencyRange: { min: 1, max: 350 },
    currencyType: 'gp',
    uniqueDrop: { name: "Merchant's Permit", dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorF:Bob_The_Farmer',
    name: 'Bob the Farmer',
    area: "Farmer's Market",
    realmId: ThievingRealmId.MELVOR,
    level: 39,
    baseExperience: 36,
    maxHit: 137,
    perception: 420,
    currencyRange: { min: 1, max: 400 },
    currencyType: 'gp',
    uniqueDrop: { name: "Bob's Gloves", dropQuantity: { min: 1, max: 1 } },
  },
  // Port of Lemvor
  {
    id: 'melvorF:Dock_Hand',
    name: 'Dock Hand',
    area: 'Port of Lemvor',
    realmId: ThievingRealmId.MELVOR,
    level: 45,
    baseExperience: 42,
    maxHit: 119,
    perception: 375,
    currencyRange: { min: 1, max: 375 },
    currencyType: 'gp',
    uniqueDrop: { name: "Sailor's Top", dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorF:Fisherman',
    name: 'Fisherman',
    area: 'Port of Lemvor',
    realmId: ThievingRealmId.MELVOR,
    level: 54,
    baseExperience: 46,
    maxHit: 101,
    perception: 400,
    currencyRange: { min: 1, max: 450 },
    currencyType: 'gp',
  },
  // Cave of Giants
  {
    id: 'melvorF:Troll',
    name: 'Troll',
    area: 'Cave of Giants',
    realmId: ThievingRealmId.MELVOR,
    level: 49,
    baseExperience: 50,
    maxHit: 151,
    perception: 450,
    currencyRange: { min: 1, max: 425 },
    currencyType: 'gp',
  },
  {
    id: 'melvorF:Cyclops',
    name: 'Cyclops',
    area: 'Cave of Giants',
    realmId: ThievingRealmId.MELVOR,
    level: 57,
    baseExperience: 53,
    maxHit: 173,
    perception: 520,
    currencyRange: { min: 1, max: 475 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Cave Giant Boots', dropQuantity: { min: 1, max: 1 } },
  },
  // Outskirts
  {
    id: 'melvorF:Lumberjack',
    name: 'Lumberjack',
    area: 'Outskirts',
    realmId: ThievingRealmId.MELVOR,
    level: 61,
    baseExperience: 62,
    maxHit: 155,
    perception: 480,
    currencyRange: { min: 1, max: 500 },
    currencyType: 'gp',
    uniqueDrop: { name: "Lumberjack's Top", dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorF:Miner',
    name: 'Miner',
    area: 'Outskirts',
    realmId: ThievingRealmId.MELVOR,
    level: 70,
    baseExperience: 73,
    maxHit: 180,
    perception: 600,
    currencyRange: { min: 1, max: 550 },
    currencyType: 'gp',
    uniqueDrop: { name: "Miner's Helmet", dropQuantity: { min: 1, max: 1 } },
  },
  // Fort
  {
    id: 'melvorF:Squire',
    name: 'Squire',
    area: 'Fort',
    realmId: ThievingRealmId.MELVOR,
    level: 66,
    baseExperience: 67,
    maxHit: 169,
    perception: 550,
    currencyRange: { min: 1, max: 525 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Training Shield', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorF:Knight',
    name: 'Knight',
    area: 'Fort',
    realmId: ThievingRealmId.MELVOR,
    level: 88,
    baseExperience: 107,
    maxHit: 241,
    perception: 820,
    currencyRange: { min: 1, max: 750 },
    currencyType: 'gp',
    uniqueDrop: { name: "Knight's Defender", dropQuantity: { min: 1, max: 1 } },
  },
  // Wizard Tower
  {
    id: 'melvorF:Acolyte',
    name: 'Acolyte',
    area: 'Wizard Tower',
    realmId: ThievingRealmId.MELVOR,
    level: 75,
    baseExperience: 76,
    maxHit: 162,
    perception: 575,
    currencyRange: { min: 1, max: 575 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Book of Scholars', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorF:Wizard',
    name: 'Wizard',
    area: 'Wizard Tower',
    realmId: ThievingRealmId.MELVOR,
    level: 84,
    baseExperience: 95,
    maxHit: 216,
    perception: 750,
    currencyRange: { min: 1, max: 700 },
    currencyType: 'gp',
    uniqueDrop: {
      name: 'Amulet of Incantation',
      dropQuantity: { min: 1, max: 1 },
    },
  },
  // Royal Castle
  {
    id: 'melvorF:Court_Jester',
    name: 'Court Jester',
    area: 'Royal Castle',
    realmId: ThievingRealmId.MELVOR,
    level: 79,
    baseExperience: 82,
    maxHit: 198,
    perception: 715,
    currencyRange: { min: 1, max: 625 },
    currencyType: 'gp',
    uniqueDrop: { name: "Jester's Hat", dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorF:Princess',
    name: 'Princess',
    area: 'Royal Castle',
    realmId: ThievingRealmId.MELVOR,
    level: 92,
    baseExperience: 120,
    maxHit: 266,
    perception: 890,
    currencyRange: { min: 1, max: 850 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Jadestone', dropQuantity: { min: 300, max: 300 } },
  },
  {
    id: 'melvorF:King',
    name: 'King',
    area: 'Royal Castle',
    realmId: ThievingRealmId.MELVOR,
    level: 95,
    baseExperience: 133,
    maxHit: 306,
    perception: 950,
    currencyRange: { min: 1, max: 1000 },
    currencyType: 'gp',
    uniqueDrop: {
      name: 'Gold Crested Shield',
      dropQuantity: { min: 1, max: 1 },
    },
  },
];

export const TOTH_TARGETS: ThievingTarget[] = [
  // Lost Ruins
  {
    id: 'melvorTotH:Explorer',
    name: 'Explorer',
    area: 'Lost Ruins',
    realmId: ThievingRealmId.MELVOR,
    level: 100,
    baseExperience: 184,
    maxHit: 290,
    perception: 1000,
    currencyRange: { min: 1, max: 1050 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Grappling Hook', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorTotH:Adventurer',
    name: 'Adventurer',
    area: 'Lost Ruins',
    realmId: ThievingRealmId.MELVOR,
    level: 105,
    baseExperience: 235,
    maxHit: 390,
    perception: 1055,
    currencyRange: { min: 1, max: 1185 },
    currencyType: 'gp',
    uniqueDrop: {
      name: "Adventurer's Backpack",
      dropQuantity: { min: 1, max: 1 },
    },
  },
  {
    id: 'melvorTotH:Treasure_Hunter',
    name: 'Treasure Hunter',
    area: 'Lost Ruins',
    realmId: ThievingRealmId.MELVOR,
    level: 110,
    baseExperience: 309,
    maxHit: 440,
    perception: 1135,
    currencyRange: { min: 1, max: 1365 },
    currencyType: 'gp',
    uniqueDrop: { name: "Hunter's Journal", dropQuantity: { min: 1, max: 1 } },
  },
  // Undead Palace
  {
    id: 'melvorTotH:Necromancer',
    name: 'Necromancer',
    area: 'Undead Palace',
    realmId: ThievingRealmId.MELVOR,
    level: 102,
    baseExperience: 198,
    maxHit: 345,
    perception: 1040,
    currencyRange: { min: 1, max: 1090 },
    currencyType: 'gp',
    uniqueDrop: {
      name: "Necromancer's Crown",
      dropQuantity: { min: 1, max: 1 },
    },
  },
  {
    id: 'melvorTotH:Dark_Knight',
    name: 'Dark Knight',
    area: 'Undead Palace',
    realmId: ThievingRealmId.MELVOR,
    level: 108,
    baseExperience: 257,
    maxHit: 365,
    perception: 1110,
    currencyRange: { min: 1, max: 1240 },
    currencyType: 'gp',
    uniqueDrop: {
      name: 'Dark Blade Defender',
      dropQuantity: { min: 1, max: 1 },
    },
  },
  // Desert
  {
    id: 'melvorTotH:Pilgrim',
    name: 'Pilgrim',
    area: 'Desert',
    realmId: ThievingRealmId.MELVOR,
    level: 104,
    baseExperience: 215,
    maxHit: 320,
    perception: 1080,
    currencyRange: { min: 1, max: 1135 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Amulet of Prayers', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorTotH:Travelling_Merchant',
    name: 'Travelling Merchant',
    area: 'Desert',
    realmId: ThievingRealmId.MELVOR,
    level: 112,
    baseExperience: 339,
    maxHit: 480,
    perception: 1160,
    currencyRange: { min: 1, max: 1435 },
    currencyType: 'gp',
    uniqueDrop: {
      name: "Traveller's Compass",
      dropQuantity: { min: 2000, max: 2000 },
    },
  },
  // Mushroom Forest
  {
    id: 'melvorTotH:Sage',
    name: 'Sage',
    area: 'Mushroom Forest',
    realmId: ThievingRealmId.MELVOR,
    level: 110,
    baseExperience: 282,
    maxHit: 410,
    perception: 1095,
    currencyRange: { min: 1, max: 1300 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Potion Stirrer', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorTotH:Madremonte',
    name: 'Madremonte',
    area: 'Mushroom Forest',
    realmId: ThievingRealmId.MELVOR,
    level: 116,
    baseExperience: 413,
    maxHit: 525,
    perception: 1250,
    currencyRange: { min: 1, max: 1590 },
    currencyType: 'gp',
    uniqueDrop: {
      name: 'Crown of Madremonte',
      dropQuantity: { min: 1, max: 1 },
    },
  },
  // Twilight
  {
    id: 'melvorTotH:Vampire',
    name: 'Vampire',
    area: 'Twilight',
    realmId: ThievingRealmId.MELVOR,
    level: 114,
    baseExperience: 371,
    maxHit: 465,
    perception: 1185,
    currencyRange: { min: 1, max: 1510 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Blood Ring', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorTotH:Vampire_Lord',
    name: 'Vampire Lord',
    area: 'Twilight',
    realmId: ThievingRealmId.MELVOR,
    level: 118,
    baseExperience: 503,
    maxHit: 550,
    perception: 1300,
    currencyRange: { min: 1, max: 1670 },
    currencyType: 'gp',
    uniqueDrop: { name: 'Vampiric Cloak', dropQuantity: { min: 1, max: 1 } },
  },
];

export const ABYSSAL_TARGETS: ThievingTarget[] = [
  // Crimson Village
  {
    id: 'melvorItA:Turned_Man',
    name: 'Turned Man',
    area: 'Crimson Village',
    realmId: ThievingRealmId.ABYSSAL,
    level: 1,
    baseExperience: 1052,
    maxHit: 4750,
    perception: 1020,
    currencyRange: { min: 1, max: 15 },
    currencyType: 'ap',
  },
  {
    id: 'melvorItA:Turned_Woman',
    name: 'Turned Woman',
    area: 'Crimson Village',
    realmId: ThievingRealmId.ABYSSAL,
    level: 4,
    baseExperience: 1348,
    maxHit: 7500,
    perception: 1070,
    currencyRange: { min: 1, max: 30 },
    currencyType: 'ap',
    uniqueDrop: {
      name: 'Piece Collector Amulet',
      dropQuantity: { min: 1, max: 1 },
    },
  },
  {
    id: 'melvorItA:Turned_Farmer',
    name: 'Turned Farmer',
    area: 'Crimson Village',
    realmId: ThievingRealmId.ABYSSAL,
    level: 13,
    baseExperience: 2266,
    maxHit: 11000,
    perception: 1160,
    currencyRange: { min: 1, max: 75 },
    currencyType: 'ap',
    uniqueDrop: { name: 'Abyssal Scythe', dropQuantity: { min: 1, max: 1 } },
  },
  // Blighted Reach
  {
    id: 'melvorItA:Blighted_Dryad',
    name: 'Blighted Dryad',
    area: 'Blighted Reach',
    realmId: ThievingRealmId.ABYSSAL,
    level: 8,
    baseExperience: 1657,
    maxHit: 8500,
    perception: 1120,
    currencyRange: { min: 1, max: 80 },
    currencyType: 'ap',
    uniqueDrop: { name: 'Blighted Staff', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorItA:Blighted_Treant',
    name: 'Blighted Treant',
    area: 'Blighted Reach',
    realmId: ThievingRealmId.ABYSSAL,
    level: 20,
    baseExperience: 2721,
    maxHit: 15500,
    perception: 1210,
    currencyRange: { min: 1, max: 200 },
    currencyType: 'ap',
    uniqueDrop: {
      name: 'Blighted Roots Seed',
      dropQuantity: { min: 5, max: 5 },
    },
  },
  // Shadeveil Maze
  {
    id: 'melvorItA:Dark_Shade',
    name: 'Dark Shade',
    area: 'Shadeveil Maze',
    realmId: ThievingRealmId.ABYSSAL,
    level: 16,
    baseExperience: 2209,
    maxHit: 13000,
    perception: 1170,
    currencyRange: { min: 1, max: 120 },
    currencyType: 'ap',
    uniqueDrop: { name: 'Shade Key', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorItA:Dark_Wraithlurker',
    name: 'Dark Wraithlurker',
    area: 'Shadeveil Maze',
    realmId: ThievingRealmId.ABYSSAL,
    level: 24,
    baseExperience: 2914,
    maxHit: 18000,
    perception: 1290,
    currencyRange: { min: 1, max: 270 },
    currencyType: 'ap',
    uniqueDrop: { name: 'Lurker Gem', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorItA:Dark_Shadowmancer',
    name: 'Dark Shadowmancer',
    area: 'Shadeveil Maze',
    realmId: ThievingRealmId.ABYSSAL,
    level: 31,
    baseExperience: 3673,
    maxHit: 24000,
    perception: 1380,
    currencyRange: { min: 1, max: 470 },
    currencyType: 'ap',
    uniqueDrop: { name: 'Shadeveil Cape', dropQuantity: { min: 1, max: 1 } },
  },
  // Withering Ruins
  {
    id: 'melvorItA:Withering_Gargoyle',
    name: 'Withering Gargoyle',
    area: 'Withering Ruins',
    realmId: ThievingRealmId.ABYSSAL,
    level: 27,
    baseExperience: 3265,
    maxHit: 21000,
    perception: 1380,
    currencyRange: { min: 1, max: 330 },
    currencyType: 'ap',
    uniqueDrop: { name: 'Withering Gem', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorItA:Withering_Golem',
    name: 'Withering Golem',
    area: 'Withering Ruins',
    realmId: ThievingRealmId.ABYSSAL,
    level: 34,
    baseExperience: 4039,
    maxHit: 27000,
    perception: 1430,
    currencyRange: { min: 1, max: 630 },
    currencyType: 'ap',
    uniqueDrop: { name: 'Golem Gloves', dropQuantity: { min: 1, max: 1 } },
  },
  // Silent Crypt
  {
    id: 'melvorItA:Silent_Poltergeist',
    name: 'Silent Poltergeist',
    area: 'Silent Crypt',
    realmId: ThievingRealmId.ABYSSAL,
    level: 38,
    baseExperience: 4372,
    maxHit: 31000,
    perception: 1380,
    currencyRange: { min: 1, max: 800 },
    currencyType: 'ap',
    uniqueDrop: {
      name: 'Silent Essence',
      dropQuantity: { min: 300, max: 300 },
    },
  },
  {
    id: 'melvorItA:Silent_Wanderer',
    name: 'Silent Wanderer',
    area: 'Silent Crypt',
    realmId: ThievingRealmId.ABYSSAL,
    level: 42,
    baseExperience: 5104,
    maxHit: 35000,
    perception: 1480,
    currencyRange: { min: 1, max: 950 },
    currencyType: 'ap',
    uniqueDrop: { name: 'Silent Boots', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorItA:Silent_Keeper',
    name: 'Silent Keeper',
    area: 'Silent Crypt',
    realmId: ThievingRealmId.ABYSSAL,
    level: 50,
    baseExperience: 5732,
    maxHit: 41000,
    perception: 1600,
    currencyRange: { min: 1, max: 1250 },
    currencyType: 'ap',
    uniqueDrop: { name: 'Skeleton Key Ring', dropQuantity: { min: 1, max: 1 } },
  },
  // Void Vaults
  {
    id: 'melvorItA:Void_Envoy',
    name: 'Void Envoy',
    area: 'Void Vaults',
    realmId: ThievingRealmId.ABYSSAL,
    level: 46,
    baseExperience: 5537,
    maxHit: 37000,
    perception: 1530,
    currencyRange: { min: 1, max: 1050 },
    currencyType: 'ap',
    uniqueDrop: { name: 'Voidtaker Amulet', dropQuantity: { min: 1, max: 1 } },
  },
  {
    id: 'melvorItA:Void_Shambler',
    name: 'Void Shambler',
    area: 'Void Vaults',
    realmId: ThievingRealmId.ABYSSAL,
    level: 54,
    baseExperience: 5886,
    maxHit: 43000,
    perception: 1750,
    currencyRange: { min: 1, max: 1450 },
    currencyType: 'ap',
    uniqueDrop: {
      name: 'Void Shambler Cape',
      dropQuantity: { min: 1, max: 1 },
    },
  },
  {
    id: 'melvorItA:Void_Gazer',
    name: 'Void Gazer',
    area: 'Void Vaults',
    realmId: ThievingRealmId.ABYSSAL,
    level: 57,
    baseExperience: 7742,
    maxHit: 45000,
    perception: 1900,
    currencyRange: { min: 1, max: 1600 },
    currencyType: 'ap',
    uniqueDrop: { name: 'Void Lens', dropQuantity: { min: 1, max: 1 } },
  },
];

export const ALL_TARGETS: ThievingTarget[] = [
  ...MELVOR_TARGETS,
  ...TOTH_TARGETS,
  ...ABYSSAL_TARGETS,
];
